threefoldtech/freeflow_twin_main

src/plugins/Router.ts
src/store/browserStore.ts

setHasBrowserBeenStartedOnce werd geimporteerd vanuit de verkeerde file.

Hotfix, bad import

---

src/components/MessageCard.vue

Chat bubbles are aligned properly on desktop now

---

src/components/GroupManagement.vue
src/components/Sidebar.vue
src/views/app/Conversation.vue

https://user-images.githubusercontent.com/56439373/137729241-df11385c-8701-4a7e-ab36-1da3ef2e23ec.mp4

Implemented a new design for the sidebar

---

src/components/MessageContentType/FileShareContent.vue
src/components/fileBrowser/EditShare.vue
src/store/fileBrowserStore.ts
src/views/app/FileBrowser.vue

- Edit share now works again
- Potential for duplicated button

prio fix, edit share now show when you click an item in chat +potential button fix

---

src/components/Dialog.vue
src/components/MessageBox.vue
src/components/MessageContentType/ImageContent.vue
src/plugins/Router.ts
src/views/app/Conversation.vue

- Make dialogs smaller on ultrawide monitors
- Conversation are scrolled to the bottom, when you scroll up more messages get loaded
- Made images smaller in height
- Last chat is saved (chats that don't exist redirect to /whisper)

UX/UI Improvements

---

src/components/UserConfigDialog.vue

Show blocked users in dialog

---

src/components/Dashboard/CreatePost.vue
src/components/MessageCard.vue
src/components/MessageContent.vue
src/components/MessageContentType/FileContent.vue
src/components/MessageContentType/FileShareContent.vue
src/components/Spinner.vue
src/components/fileBrowser/FileTable.vue
src/components/fileBrowser/MainActionButtons.vue
src/components/fileBrowser/SharedContent.vue
src/components/fileBrowser/TopBar.vue
src/components/fileBrowser/ViewSelect.vue
src/plugins/Router.ts
src/store/fileBrowserStore.ts
src/views/app/Dashboard.vue

- Fixed race condition issue saved attachments + added loaders

Fixed race condition issue saved attachments + added loaders

---

src/components/Dashboard/CreatePost.vue
src/components/Dashboard/Post.vue
src/components/MessageCard.vue
src/components/MessageContentType/FileContent.vue
src/components/fileBrowser/ResultsTable.vue
src/components/fileBrowser/ViewSelect.vue
src/services/fileBrowserService.ts
src/views/app/Kutana.vue

Small changes in behaviour

---

src/components/ChatInput.vue
src/components/Dashboard/Post.vue
src/components/Dashboard/PostComment.vue
src/components/Dashboard/SharePostDialog.vue
src/components/Dialog.vue
src/components/MessageContentType/FileShareContent.vue
src/components/MessageContentType/PostShareContent.vue
src/components/fileBrowser/FileTable.vue
src/components/fileBrowser/ResultsTable.vue
src/components/fileBrowser/SharedContent.vue
src/services/fileBrowserService.ts
src/services/socialService.ts
src/store/fileBrowserStore.ts
src/views/app/Conversation.vue

- Added esc button
- Fixed overflow issue
- Fixed kutana username in conversation
- Fixed usage of emoji's in chat
- Fixed major issues with not opening files from shared items

Dev 24dec fixes

---

src/views/app/Browser.vue

It now only loads the Iframe if you are on the Glass navigation.

#286 fixed navigation not working when changing quickly from Glass

---

src/components/Dashboard/CommentsContainer.vue
src/components/Dashboard/PostComment.vue
src/services/socialService.ts
src/store/socialStore.ts

Since you can't like comments yet i hid the like button for now. And made the frontend ready so the API can be implemented in the backend

#290 added more typings and made ready for the backend

---

src/components/Dashboard/CreatePost.vue

#419 make it possible to create a post with only an image

---

src/store/socketStore.ts

#373 remove post from the feed for all contacts if it gets deleted

---

src/store/socketStore.ts

The branch may be deleted
Backend PR: https://github.com/threefoldtech/digitaltwin-lib/pull/46

#498 Implement realtime status updates

---

src/views/app/Conversation.vue

Now shows 2 different dialog depending on the user roles

#497 show correct leave dialog for users

---

src/components/ChatList.vue
src/views/app/Chat.vue

I feel like only the title on the left needed to change, for the rest it was clear for me that I did not have any contacts.

#490 changed title for whisper empty state

---

src/components/Dashboard/CommentHoverPanel.vue
src/components/GroupManagement.vue
src/components/MessageBox.vue
src/components/MessageCard.vue
src/views/app/Conversation.vue

#485 show profile popup in chat

---

apps/frontend/src/components/ChatCard.vue
apps/frontend/src/layout/AppLayout.vue
apps/frontend/src/store/chatStore.ts

#534 fix chat read

---

apps/backend/src/features/quantum/quantum.service.ts
apps/spawner/frontend/src/views/Home.vue

Self hosting instructions

---

apps/frontend/src/components/MessageContent.vue
apps/frontend/src/components/MessageContentType/ImageContent.vue
apps/frontend/src/components/MessageContentType/VideoContent.vue
apps/frontend/src/components/fileBrowser/FileTable.vue
apps/frontend/src/services/contentService.ts

If it is not a video or image it goes to onlyoffice

Video support

---

apps/backend/src/features/message/states/system-message.state.ts
apps/backend/src/features/quantum/quantum.service.ts
apps/frontend/src/components/fileBrowser/Breadcrumbs.vue

- fixed problem with creating folder
- leave chat not working properly #656 #657 
This is needed to prevent @dragleave from being fired when you hover over child element. Tried several other solutions but didn't work

Drag file to home

---

apps/spawner/frontend/yarn.lock

Reverts threefoldtech/twin_aydo#634

Revert "build(deps): bump shell-quote from 1.7.2 to 1.7.3 in /apps/spawner/frontend"

---

README.md
apps/backend/src/features/post/dtos/delete-comment.dto.ts
apps/backend/src/features/post/dtos/request/like-comment.dto.ts
apps/backend/src/features/post/post.controller.ts
apps/backend/src/features/post/post.service.ts
apps/frontend/src/components/Dashboard/PostComment.vue
apps/frontend/src/services/socialService.ts

PR for both like/unlike comment and delete comment (#711 , #712 )

#712 like/unlike comment

---

apps/backend/src/config/config.ts
apps/backend/src/features/api/api.service.ts
apps/backend/src/features/chat/chat.service.ts
apps/backend/src/features/contact/contact.controller.ts
apps/backend/src/features/contact/contact.service.ts
apps/backend/src/features/contact/dtos/contact.dto.ts
apps/backend/src/features/contact/models/contact.model.ts
apps/backend/src/features/contact/repositories/contact-redis.repository.ts
apps/backend/src/features/post/post.service.ts
apps/backend/src/features/user/user.controller.ts
apps/backend/src/features/user/user.gateway.ts

If you load the page it will check which containers are still running of your contacts. And sets the property 'containerIsOffline'
When you load the posts it will check if that property is true, otherwise it will try to get the posts (also with timeout).

Post not loading

---

apps/backend/src/features/post/post.service.ts
apps/frontend/src/components/fileBrowser/FileTable.vue
apps/frontend/src/store/fileBrowserStore.ts

2 bug fixes
- Delete all replies of deleted comment
- Select files

Unable select files

---

apps/backend/src/features/api/api.service.ts
apps/backend/src/features/app/app.module.ts
apps/backend/src/features/contact/contact.service.ts
apps/backend/src/features/container/container.controller.ts
apps/backend/src/features/container/container.module.ts
apps/backend/src/features/container/container.service.ts
apps/frontend/src/services/socialService.ts
apps/frontend/src/views/Home.vue

Reverts threefoldtech/twin_aydo#764

Revert "Revert "possible solution (needs be tested on staging)""

---

apps/frontend/src/components/Dashboard/CommentHoverPanel.vue

Contacts didn't get updated in the dialog unless you close and reopen it.

#793 use reactive state

---

apps/frontend/src/components/Dashboard/Post.vue
apps/frontend/src/components/Dashboard/PostComment.vue
apps/frontend/src/components/GroupManagement.vue
apps/frontend/src/components/MessageBox.vue
apps/frontend/src/components/MessageContentType/PostShareContent.vue
apps/frontend/src/views/app/Conversation.vue
apps/frontend/src/views/app/FileBrowser.vue

fixed multiple layout problems, see the commit msg for references to the issues.

Layout problems

---

apps/backend/src/features/post/post.service.ts

fix for removing nested comments

#899 same changes to removeComment as with replaceComment (for #864)
